import { test } from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import { verifyPassword } from '../../src/auth/password.js';
import { fileURLToPath } from 'node:url';

const root = name => fileURLToPath(new URL(`../../${name}`, import.meta.url));
const read = name => fs.readFileSync(root(name), 'utf8');

const NPM_BUILTINS = ['install', 'ci'];

// --- AGENTS.md states the rule the code now enforces ----------------------

test('AGENTS.md | the "No authentication" constraint is gone', () => {
  const agents = read('AGENTS.md');

  assert.ok(
    !/\*\*No authentication:\*\*/.test(agents),
    'the app has authentication now; the constraint must not still say otherwise'
  );
});

test('AGENTS.md | names both roles and what separates them', () => {
  const agents = read('AGENTS.md');

  assert.ok(/`admin`/.test(agents), 'the admin role must be named');
  assert.ok(/`orderuser`/.test(agents), 'the orderuser role must be named');
  assert.ok(/config\/users\.json/.test(agents), 'the user store must be named');
});

// --- README tells a new clone how to get in -------------------------------

test('README | has a first-run section covering the config copy', () => {
  const readme = read('README.md');

  assert.ok(/config\/users\.example\.json/.test(readme), 'the example config must be named');
  assert.ok(/config\/users\.json/.test(readme), 'the destination must be named');
  assert.ok(/npm run auth:hash/.test(readme), 'the hash tool must be documented');
});

test('README | the documented credentials are exactly the ones that work', async () => {
  const readme = read('README.md');
  const example = JSON.parse(read('config/users.example.json'));

  // Only the credentials table counts, not any passing mention of a role name.
  const documented = [...readme.matchAll(/^\| `([^`]+)` \| `([^`]+)` \| `([^`]+)` \|/gm)]
    .map(([, username, password, role]) => ({ username, password, role }));

  assert.strictEqual(
    documented.length,
    example.users.length,
    `the table documents ${documented.length} logins but the example ships ${example.users.length}`
  );

  for (const entry of documented) {
    const user = example.users.find(u => u.username === entry.username);
    assert.ok(user, `the README documents "${entry.username}", which the example does not contain`);
    assert.strictEqual(user.role, entry.role, `role documented for "${entry.username}"`);

    // The strongest check available: the password in the table really logs in.
    assert.strictEqual(
      await verifyPassword(entry.password, user, example.hash),
      true,
      `the password the README gives for "${entry.username}" does not match the example hash`
    );
  }
});

test('README | no longer advertises the app as having no user accounts', () => {
  const readme = read('README.md');

  assert.ok(!/No user accounts/i.test(readme), 'that line predates the login screen');
});

test('README | warns that a forgotten password is regenerated, not recovered', () => {
  const readme = read('README.md');

  assert.ok(
    /forgot|forgotten|lost/i.test(readme),
    'the only recovery path is npm run auth:hash, which the README should say'
  );
});

// --- the docs describe things that exist ----------------------------------

test('Docs | every npm command the README shows exists in package.json', () => {
  const readme = read('README.md');
  const { scripts } = JSON.parse(read('package.json'));

  const mentioned = [...readme.matchAll(/npm (?:run )?([a-z][a-z0-9:-]*)/g)].map(m => m[1]);
  assert.ok(mentioned.length > 0, 'the README should show how to run the app');

  for (const command of new Set(mentioned)) {
    if (NPM_BUILTINS.includes(command)) continue;
    assert.ok(scripts[command], `README mentions "npm run ${command}" but package.json has no such script`);
  }
});

test('Docs | every repo file the README points at is really there', () => {
  const readme = read('README.md');

  const paths = [...readme.matchAll(/(?:config|scripts|src)\/[A-Za-z0-9._/-]+/g)].map(m => m[0]);
  assert.ok(paths.length > 0, 'the first-run section should reference real files');

  for (const relative of new Set(paths)) {
    // config/users.json is generated by the operator and git-ignored.
    if (relative === 'config/users.json') continue;
    assert.ok(fs.existsSync(root(relative)), `README references ${relative}, which does not exist`);
  }
});
